---
output:
  html_document:
    keep_md: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
iframe_htmlwidget <- function(htmlwidget) {

  html_path <- knitr::fig_path("html") # get the path like knitr would do
  # TODO: should I ensure this is always a relative path?
  #       it seems it is, but can't find assurances

  htmlwidgets::saveWidget(
    widget = htmlwidget, 
    file = normalizePath(html_path), # full path, otherwise it'll complain
    selfcontained = FALSE, lib = "widgets"
    # selfcontained = TRUE, but still the dependencies are copied to te figures
    # dir so you need to exclude them via .gitignore to avoid commiting jquery,
    # plotly, and all other libraries in version control
  )

  # If local preview, you want the iframe to point to an absolute path because
  # "when you render from within RStudio using the Knit button the preview HTML 
  # is written to a temporary directory and then automatically displayed by 
  # RStudio.". 
  # https://rmarkdown.rstudio.com/github_document_format.html#HTML_Preview
  # 
  # They handle the images well, but they are not aware of the 
  # iframe, and therefore, the saved htmlwidget will not be found.
  # To overcome this, and absolute path in your system will do. However, that
  # won't work when it's online, so before pushing this to github, you should
  # set html_preview = FALSE and this little function will leave the iframe
  # with a relative path
  iframe_src_path <- ifelse(
    test = isTRUE(rmarkdown::metadata$output$github_document$html_preview),
    yes = normalizePath(html_path),
    no = html_path
  )

  htmltools::tags$iframe(
    src = iframe_src_path,
    width = "70%",
    height = "600",
    scrolling = "no",
    seamless = "seamless",
    frameBorder = "0",
    style = "display: block; margin: auto;"
  )
  # TODO: consider also not including assets in the html file but rather cdn links
  # see for example this SO question for ideas
  # https://stackoverflow.com/questions/51213463/how-to-skip-writing-dependencies-in-htmlwidgetssavewidget
  # plot_html_widget$dependencies[[2]]$src$file <- NULL
  # plot_html_widget$dependencies[[2]]$src$href <- "https://code.jquery.com/"s
}
```

# `rtists`

<!-- badges: start -->
<!-- badges: end -->

The goal of `rtists` is to provide visualization tools for tissue integrity superimposed on tractography streamlines.

## Installation

You can install the development version of rtists from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("astamm/rtists")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(rtists)
library(future)
plan(multisession)
out <- autoplotly::autoplotly(uf_left)
plan(sequential)
html_path <- knitr::fig_path("html")
print(html_path)
htmlwidgets::saveWidget(
    widget = out, 
    file = normalizePath(html_path), 
    selfcontained = TRUE
  )
htmltools::tags$iframe(
    src = html_path,
    width = "70%",
    height = "600",
    scrolling = "no",
    seamless = "seamless",
    frameBorder = "0",
    style = "display: block; margin: auto;"
  )
```
